### PR TITLE
IE fixes

### LINKED ISSUE #518: Test compatibility on IE
Test the site on IE8-10 to follow GDS guidelines for functionality. Testing on IE11 for being 'compliant'.

### LINKED ISSUE #545: Pros and cons visibility on IE8
View pros and cons button does not work on resources so the pros and cons are not showing anywhere

Because [media queries aren't supported prior to IE9](https://stackoverflow.com/questions/5769493/ie8-support-for-css-media-query), IE8 defaults to `display:block` on the `div` containing the View pros/cons buttons, making it visible. Additionally, the pros and cons list defaults to `display:none`.

Instead we will need to have the default setting as:
- [x] View pros and cons button is `display:none`
- [x] Pros and cons list is `display:table`
- [x] JS will then be used to detect:
  - [x] if the pros and cons are on the current page
  - [x] if it's mobile view
  - [x] if both of the above are true, then reverse pros & cons buttons to `display: block` and pros and cons list to `display:none`

The JS will then work as it does now with toggling the class to show or hide the pros and cons list.

### PR DESCRIPTION
**Pull request by katbow**
#518 fixes small bugs for ie 8-11

#545 Change pros and cons so it works without JavaScript **and** media queries.

### CODE REVIEW

File: cms/static/js/view_pros_cons.js [hunk 1]
```diff
@@ -19,4 +19,29 @@ function proConListeners() {
...
+// hides the list of pros and cons
+function reverseListVisibility (el) {
+  removeClasses(el, ['dt']);
+  addClasses(el, ['dn']);
+}
+
+// checks if pros and cons are on the page that's being view, and if it's mobile
+function mobileProsAndCons () {
+  if (selectAll('.pros_cons').length > 0 && isMobile()) {
+    selectAll('.pros_cons').forEach(function (el) {
```
Comment (SimonLab) [inline cms/static/js/view_pros_cons.js:37]: Does IE8 support forEach? :thinking:

**Review by SimonLab — COMMENTED** [review]
Just one question concerning the support of ```forEach``` otherwise looks good to me, @katbow @Danwhy let me know your thoughts

File: cms/static/js/view_pros_cons.js (hunk 1 above)
Comment (katbow) [reply cms/static/js/view_pros_cons.js:37]: It might not, but it's been reworked so that users on IE8 can view pros and cons without JavaScript. So with this change around, it will default to the pros and cons being visible on IE8, and the JS won't need to run to view them.

**Review by SimonLab — APPROVED** [review]
LGTM
